// packages/vue/src/App.vue
<template>
  <div id="app">
    <h1>Welcome to My Vue 3 App</h1>
    <ChainProvider
      :chains="chains"
      :wallets="wallets"
      :assetLists="assets"
      :walletConnectOptions="walletConnectOptions"
      :walletModal="CustomModal"
    >
      <router-view />
    </ChainProvider>
  </div>
</template>

<script setup>
import ChainProvider from "./providers/ChainProvider.vue";
import CustomModal from "./components/CustomModal.vue";
import { assets as _assets, chains as _chains } from "chain-registry";
// import { wallets as _wallets } from "@cosmos-kit/keplr";
import { wallets as keplrExtension } from "@cosmos-kit/keplr-extension";

const chains = [..._chains];
const wallets = [...keplrExtension];
const assets = [..._assets];
const walletConnectOptions = {
  signClient: {
    projectId: "a8510432ebb71e6948cfd6cde54b70f7",
    relayUrl: "wss://relay.walletconnect.org",
    metadata: {
      name: "CosmosKit Example",
      description: "CosmosKit test dapp",
      url: "https://test.cosmoskit.com/",
      icons: [
        "https://raw.githubusercontent.com/cosmology-tech/cosmos-kit/main/packages/docs/public/favicon-96x96.png",
      ],
    },
  },
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// packages/docs/pages/_app.tsx
import "../styles/globals.css";
import type { AppProps } from "next/app";
// import { defaultTheme, ChainProvider } from "@cosmos-kit/react";
import { ChakraProvider } from "@chakra-ui/react";
import { assets, chains } from "chain-registry";
// import { wallets as cosmostationWallets } from "@cosmos-kit/cosmostation";
// import { wallets as keplrWallet } from "@cosmos-kit/keplr";
// import { wallets as leapwallets } from "@cosmos-kit/leap";
// import { wallets as frontierwallets } from "@cosmos-kit/frontier";
// import { wallets as vectisWallets } from "@cosmos-kit/vectis";
// import { wallets as xdefiWallets } from "@cosmos-kit/xdefi-extension";
// import { wallets as omniWallets } from "@cosmos-kit/omni";
// import { wallets as trustWallets } from "@cosmos-kit/trust";
import "nextra-theme-docs/style.css";
import React from "react";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    // <ChakraProvider theme={defaultTheme}>
    //   <ChainProvider
    //     chains={chains}
    //     assetLists={assets}
    //     wallets={[
    //       ...keplrWallet,
    //       ...cosmostationWallets,
    //       ...leapwallets,
    //       ...vectisWallets,
    //       // ...xdefiWallets,
    //       ...omniWallets,
    //       ...trustWallets,
    //       ...frontierwallets,
    //     ]}
    //     wrappedWithChakra={true}
    //     walletConnectOptions={{
    //       signClient: {
    //         projectId: "61e6745dc9a852e0ed9ba60d28212357",
    //         relayUrl: "wss://relay.walletconnect.org",
    //         metadata: {
    //           name: "CosmosKit Example",
    //           description: "CosmosKit Docs",
    //           url: "https://docs.cosmoskit.com/",
    //           icons: [
    //             "https://raw.githubusercontent.com/cosmology-tech/cosmos-kit/main/packages/docs/public/favicon-96x96.png",
    //           ],
    //         },
    //       },
    //     }}
    //   >
    <Component {...pageProps} />
    //   </ChainProvider>
    // </ChakraProvider>
  );
}

export default MyApp;
