// packages/example-lite/components/custom-modal.tsx
import { WalletModalProps, WalletStatus } from "@cosmos-kit/core";
import React from "react";
import { Badge, Button, Modal, Stack } from "react-bootstrap";

export const CustomModal = ({
  isOpen,
  setOpen,
  walletRepo,
}: WalletModalProps) => {
  const onCloseModal = () => {
    setOpen(false);
  };

  return (
    <div
      className="modal show"
      style={{ display: "block", position: "initial" }}
    >
      <Modal show={isOpen} onHide={onCloseModal}>
        <Modal.Header closeButton>
          <Modal.Title>Choose Wallet</Modal.Title>
        </Modal.Header>

        <Modal.Body>
          <Stack gap={3}>
            {walletRepo?.wallets.map(
              ({
                walletName,
                connect,
                disconnect,
                walletInfo,
                walletStatus,
                message,
              }) => {
                let button;
                switch (walletStatus) {
                  case WalletStatus.Disconnected:
                    button = <Button onClick={() => connect()}>Connect</Button>;
                    break;
                  case WalletStatus.NotExist:
                    button = <Button>Install</Button>;
                    break;
                  case WalletStatus.Connected:
                    button = (
                      <Button onClick={() => disconnect()}>Disconnect</Button>
                    );
                    break;
                  case WalletStatus.Error:
                    button = (
                      <div className="p-2 text-danger-emphasis bg-danger-subtle border border-danger-subtle rounded-3">
                        {message}
                      </div>
                    );
                    break;
                }
                return (
                  <Stack key={walletName} direction="horizontal" gap={3}>
                    <div className="p-2">
                      {walletInfo.prettyName} - {walletStatus}
                    </div>
                    <div className="p-2 ms-auto"> {button}</div>
                  </Stack>
                );
              }
            )}
          </Stack>
        </Modal.Body>
      </Modal>
    </div>
  );
};

// packages/vue/src/components/CustomModal.vue
<template>
  <el-dialog
    v-model="isOpen"
    title="Choose Wallet"
    width="60%"
    style="max-width: 400px"
    @close="onCloseModal"
    class="wallet-modal"
  >
    <el-row
      v-for="wallet in walletRepo?.wallets"
      :key="wallet.walletName"
      type="flex"
      class="wallet-row"
    >
      <el-col :span="12" class="wallet-info">
        <el-image
          :src="walletRepo.chainLogo"
          style="width: 35px; height: 35px"
        />
        <span>{{ wallet.walletInfo.prettyName }}</span>
        <span class="wallet-status">{{ wallet.walletStatus }}</span>
      </el-col>
      <el-col :span="12" class="wallet-actions">
        <template v-if="wallet.walletStatus === 'Disconnected'">
          <el-button type="primary" @click="wallet.connect">Connect</el-button>
        </template>
        <template v-else-if="wallet.walletStatus === 'NotExist'">
          <el-button type="warning">Install</el-button>
        </template>
        <template v-else-if="wallet.walletStatus === 'Connected'">
          <el-button type="success" @click="wallet.disconnect"
            >Disconnect</el-button
          >
        </template>
        <template v-else-if="wallet.walletStatus === 'Error'">
          <el-alert :title="wallet.message" type="error" />
        </template>
      </el-col>
    </el-row>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, defineProps, defineEmits, watch } from "vue";
import { ElDialog, ElRow, ElCol, ElButton, ElAlert } from "element-plus";
import type { WalletModalProps } from "@cosmos-kit/core";

const props = defineProps<WalletModalProps>();
const emit = defineEmits<{
  (e: "update:isOpen", value: boolean): void;
}>();

const isOpen = ref(props.isOpen);
const walletRepo = ref(props.walletRepo);

watch(
  () => props.isOpen,
  (newValue) => {
    isOpen.value = newValue;
  }
);

watch(
  () => props.walletRepo,
  (newValue) => {
    console.log(newValue);
    walletRepo.value = newValue;
  }
);

const onCloseModal = () => {
  props.setOpen(false);
};
</script>

<style scoped>
.wallet-modal .el-dialog__header {
  background-color: #f5f5f5;
  border-bottom: 1px solid #e0e0e0;
}

.wallet-modal .el-dialog__title {
  font-size: 18px;
  font-weight: bold;
}

.wallet-row {
  margin-bottom: 10px;
}

.wallet-info {
  display: flex;
  align-items: center;
  justify-content: space-between;
  font-size: 16px;
}

.wallet-status {
  font-size: 14px;
  color: #888;
}

.wallet-actions {
  display: flex;
  justify-content: flex-end;
}

.el-button {
  margin-left: 10px;
}

.el-alert {
  margin-top: 5px;
}
</style>
